---
name: Build and publish Docker image
on:
    push:
        branches:
            - main

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Login into DockerHub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker Image
              uses: docker/build-push-action@v6
              with:
                context: .
                push: false
                tags: |
                  ${{ secrets.DOCKER_USERNAME }}/spc-gcp:${{ github.sha }}
                  ${{ secrets.DOCKER_USERNAME }}/spc-gcp:latest
            - name: scan docker image
              uses: aquasecurity/trivy-action@0.28.0
              with:
                image-ref: ${{ secrets.DOCKER_USERNAME }}/spc-gcp:${{ github.sha }}
                format: table
                ignore-unfixed: true
            - name: publish Docker Image
              if: success()
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: |
                  ${{ secrets.DOCKER_USERNAME }}/spc-gcp:${{ github.sha }}
                  ${{ secrets.DOCKER_USERNAME }}/spc-gcp:latest
            - name: logout of docker hub
              run: docker logout
